### ISSUE TITLE
Please switch to https

### ISSUE THREAD

**Issue by jbicha** [clobrano/clobrano.github.io#1]
The popular [HTTPS Everywhere extension](https://www.eff.org/https-everywhere) uses https by default for GitHub pages. Browsers like Chrome and Firefox block some http assets when the site is requested via https. In my case, the CSS is blocked so the site is unthemed.

Please update your http references to https after making sure they work over https.

**Comment by clobrano** [comment]
I should have done it ages ago. Thanks for the reminder ;)

**Comment by clobrano** [comment]
Should be good now. If you like, could you please double check?

**Comment by jbicha** [comment]
Yes, it works good now!
